[language-server]
deno = { command = "deno", args = [ "lsp" ]}
emmet-ls = { command = "emmet-ls", args = [ "--stdio" ]}

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
environment = { "DENO_UNSTABLE_SLOPPY_IMPORTS" = "1"}

[language-server.deno-lsp.config.deno]
enable = true
unstable = true
# # unstable = ["sloppy-imports"]
# suggest.imports.hosts = { "https://deno.land" = true }

[language-server.eslint]
#

args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
# format = true
nodePath = ""
# onIgnoredFiles = "off"
# packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
# useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
# codeActionsOnSave = { mode = "all" }
experimental = {}
problems = { shortenToSingleLine = false }
# workingDirectory = { mode = "auto" }

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "rust"
auto-format = true

[[language]]
# See https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#typescript
name = "typescript"
formatter = { command = "dprint", args = [ "fmt", "--stdin", "ts" ] }
auto-format = true
language-servers = ["typescript-language-server",  "eslint"]

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--write", "--parser", "html"] }
auto-format = true
language-servers = ["vscode-html-language-server", "angular"]
# 
[[language]]
name = "tsx"
# language-servers = [ "deno", "eslint", "emmet-ls"]
language-servers = [ "deno",  "emmet-ls"]
formatter = { command = "dprint", args = [ "fmt", "--stdin", "typescript" ] }
auto-format = true

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "emmet-ls" ]
# formatter = { command = 'prettier', args = ["--parser", "html"] }
formatter = { command = "dprint", args = [ "fmt", "--stdin", "html" ] }
auto-format = true

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "emmet-ls" ]
# formatter = { command = 'prettier', args = ["--parser", "css"] }
formatter = { command = "dprint", args = [ "fmt", "--stdin", "css" ] }
auto-format = true

[[language]]
name = "json"
# formatter = { command = "prettier", args = [ "--parser", "json" ] }
formatter = { command = "dprint", args = [ "fmt", "--stdin", "json" ] }
auto-format = true

# [[language]]
# name = "sql"
# language-servers = ["sql-language-server"]
# auto-format = true

