[language-server.deno]
command = "deno"
args = ["lsp"]
config = { enable = true, line = true, unstable = true, importMap = "deno.json"}

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
environment = { "DENO_UNSTABLE_SLOPPY_IMPORTS" = "1"}

[language-server.deno-lsp.config.deno]
enable = true
unstable = true

[language-server.lua-language-server]
command = "lua-language-server"
enable = true

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "lua"
auto-format = true

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
formatter = { command = "dprint", args = [ "fmt", "--stdin", "typescript" ] }
auto-format = true

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]
formatter = { command = "dprint", args = [ "fmt", "--stdin", "tsx" ] }
auto-format = true

[[language]]
name = "jsx"
language-servers = ["typescript-language-server"]
formatter = { command = "dprint", args = [ "fmt", "--stdin", "jsx" ] }
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
formatter = { command = "dprint", args = [ "fmt", "--stdin", "javascript" ] }
auto-format = true

[[language]]
name = "html"
auto-format = true

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server" ]
auto-format = true

[[language]]
name = "json"
formatter = { command = "dprint", args = [ "fmt", "--stdin", "json" ] }
auto-format = true

# [[language]]
# name = "Dockerfile"
# formatter = { command = "dprint", args = [ "fmt", "--stdin", "Dockerfile" ] }
# auto-format = true
 

[[language]]
name = "toml"
formatter = { command = "dprint", args = [ "fmt", "--stdin", "toml" ] }
auto-format = true

[[language]]
name = "yaml"
language-servers = ["yaml-language-server"]
formatter = { command = "dprint", args = [ "fmt", "--stdin", "pretty_yaml" ] }
auto-format = true

[[language]]
name = "sql"
language-servers = ["sql-language-server"]
auto-format = true

