theme = "gruvbox"

[editor]
line-number = "relative"
mouse = true
gutters = ["diagnostics", "line-numbers", "diff", "spacer"]
true-color = true
rulers = [100]
bufferline = "always"
color-modes = true
auto-completion = true
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding"]

[editor.lsp]
# displays messages below statusline
# display-messages = true
display-inlay-hints = true

[keys.normal]
"C-k" = "kill_to_line_end"
